
#ifndef SHAREDDEFS_H
#define SHAREDDEFS_H
enum SERVER_CODES { LOGIN, SIGNUP, LOGOUT, EDIT_INFO, FORGOT_PASSWORD, START_GAME,GET_GAME_STATE,
    GET_AVAILABLE_CARDS, CHOOSE_CARD, ROUND_RESULT};
#endif //SHAREDDEFS_H
