
#ifndef SHAREDDEFS_H
#define SHAREDDEFS_H
enum SERVER_CODES { LOGIN, SIGNUP, LOGOUT, EDIT_INFO, FORGOT_PASSWORD, START_GAME,GET_INITIAL_CARDS, /* I no idea*/GET_GAME_STATE,
    GET_AVAILABLE_CARDS, CHOOSE_CARD, TIMEOUT, PAUSE_GAME, ROUND_RESULT, GAME_OVER, PAUSE_REQUESTING, EXTRA_TIME_STARTED};
#endif //SHAREDDEFS_H
